version: '3.5'

services:
  app:
    image: 'sharifulbony/mbank-report:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - postgres
      - rbbit1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/account
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=changeme
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    networks:
      - webproxy
  rbbit1:
    container_name: rabbit-mq
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbit"
      RABBITMQ_DEFAULT_PASS: "rabbit"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
    networks:
      - webproxy
    volumes:
      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
  postgres:
    hostname: postgres
    container_name: postgres
    image: 'postgres:13.1-alpine'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5432:5432"
    networks:
      - webproxy
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - webproxy
    restart: unless-stopped

networks:
  webproxy:
    driver: bridge

volumes:
    postgres:
    pgadmin:

